### ISSUE TITLE
Cannot import pytorch_pretrained_gans 

### ISSUE THREAD

**Issue by zeyuyun1** [lukemelas/pytorch-pretrained-gans#1]
I follow the tutorial and install by running 
`pip install git+https://github.com/lukemelas/pytorch-pretrained-gans`

However, I receive the following error:

>>> from pytorch_pretrained_gans import make_gan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zeyuy/miniconda3/lib/python3.8/site-packages/pytorch_pretrained_gans/__init__.py", line 5, in <module>
    from .StudioGAN import make_studiogan
  File "/home/zeyuy/miniconda3/lib/python3.8/site-packages/pytorch_pretrained_gans/StudioGAN/__init__.py", line 9, in <module>
    from .models import resnet
ModuleNotFoundError: No module named 'pytorch_pretrained_gans.StudioGAN.models'

**Comment by lukemelas** [comment]
Hello, thanks for the issue. I wanted to reply to say that I've seen your issue and I will be working on it soon (right after I finish something for a pressing deadline).

**Comment by lukemelas** [comment]
Ok -- I was able to reproduce and I believe I've fixed the error. Let me know if it works for you now. 

Also: you can always get it to work by git cloning and doing `pip install -e .`.

**Comment by zeyuyun1** [comment]
yeah it works thank you!!
