### ISSUE TITLE
Pretrained Model of BigBIGAN-256 and BigBIGAN-512

### ISSUE THREAD

**Issue by wuzhenyubuaa** [lukemelas/pytorch-pretrained-gans#3]
Hi，can you provided the **URL** of pre-trained model of BigBIGAN-256 and BigBIGAN-512. By default, we can only use the bigbigan-128.
![image](https://user-images.githubusercontent.com/40664663/131310180-213f3a7e-705f-4a30-bef4-b61b4355a3d5.png)

**Comment by lukemelas** [comment]
Hi @wuzhenyubuaa,

Unfortunately, the BigBiGAN model was only trained at 128px, not 256 or 512px -- the models you are asking for do not exist.
